// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentGradingApp.Data;

#nullable disable

namespace StudentGradingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250808203829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("StudentGradingApp.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeacherPrincipalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherPrincipalId")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatiereId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valeur")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MatiereId");

                    b.HasIndex("StudentId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("StudentGradingApp.Models.TeacherMatiere", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatiereId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeacherId", "MatiereId");

                    b.HasIndex("MatiereId");

                    b.ToTable("teacherMatieres");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Classe", b =>
                {
                    b.HasOne("StudentGradingApp.Models.Teacher", "TeacherPrincipal")
                        .WithOne("ClassePrincipale")
                        .HasForeignKey("StudentGradingApp.Models.Classe", "TeacherPrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TeacherPrincipal");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Note", b =>
                {
                    b.HasOne("StudentGradingApp.Models.Matiere", "Matiere")
                        .WithMany("Notes")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentGradingApp.Models.Student", "Student")
                        .WithMany("Notes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Student", b =>
                {
                    b.HasOne("StudentGradingApp.Models.Classe", "Classe")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("StudentGradingApp.Models.TeacherMatiere", b =>
                {
                    b.HasOne("StudentGradingApp.Models.Matiere", "Matiere")
                        .WithMany("TeacherMatieres")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentGradingApp.Models.Teacher", "Teacher")
                        .WithMany("TeacherMatieres")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Classe", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Matiere", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("TeacherMatieres");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Student", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("StudentGradingApp.Models.Teacher", b =>
                {
                    b.Navigation("ClassePrincipale");

                    b.Navigation("TeacherMatieres");
                });
#pragma warning restore 612, 618
        }
    }
}
